% compute phi = exp(Tv), using 2^N or N recursive iterations
% X, Y is the domain definition, generated by meshgrid
function phi0 = exp_mapping(v, X, Y, T, N)

dt = T / 2^N;
phi0(:, :, 1) = dt * v(:, :, 1) + X;
phi0(:, :, 2) = dt * v(:, :, 2) + Y;


for i = 1:N
    phi0 = compose_phi(phi0, phi0, X, Y);
end;


